version: '2.3'

services:
  dscensor:
    build: .
    environment:
      FLASK_ENV: development
      FLASK_APP: dscensor:app
      HOST: '//neo4j'
      PORT: 7687
      AUTH: ''
      PSWD: ''
    working_dir: /app/server
    command: python -m flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - ./dscensor:/app:ro

  neo4j:
    image: neo4j:3.5
    environment:
      NEO4J_AUTH: none
