#################################################################
# MultiQC Defaults
#################################################################
# This file contains the default configuration options
# for MultiQC. IT SHOULD NOT BE EDITED. If you want to
# change any of these config options, create a new file
# in any of the following locations:
#  1. <installation_dir>/multiqc_config.yaml (not pip or conda)
#  2. ~/.multiqc_config.yaml
#  3. <working directory>/multiqc_config.yaml
#################################################################

title: "DSCensor Genome Main Overview"
subtitle: null
intro_text: "Statistics and BUSCOs for Legume Federation Genomes"
report_comment: null
report_header_info: null
config_file: null
custom_logo: "/media/filer_public_thumbnails/filer_public/62/13/62139bfd-4b06-4685-9363-ec0512adc1cb/legfed-member.png__163x71_q85_crop_subsampling-2_upscale.png"
custom_logo_url: "https://www.legumefederation.org"
custom_logo_title: "Legume Federation"
simple_output: false
template: 'default'

table_columns_visible:
    DSMetrics:
        total_buscos: False
        complete_single_copy: False
        complete_duplicated: False
        fragmented: False
        lineage_dataset: False
        Contigs: False
        Total Gaps: False
